# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-12 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpr', '0033_update_idtools'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fpcommand',
            name='command_usage',
            field=models.CharField(choices=[(b'characterization', 'Characterization'), (b'event_detail', 'Event Detail'), (b'extraction', 'Extraction'), (b'normalization', 'Normalization'), (b'transcription', 'Transcription'), (b'validation', 'Validation'), (b'verification', 'Verification'), (b'virus_scan', 'Virus scan')], max_length=16, verbose_name='command usage'),
        ),
    ]
